opencollective: https://opencollective.com/tenancy
message: |
  Hey :wave:,
  Thank you for using our package. 
  We firmly believe that open sourcing our code improves the developer experience.
  In a pursuit to continue our work, help us by donating to our collective! :heart:
labels:
  - Support
